### ISSUE TITLE
Regions - List of all Regions Page 

### ISSUE THREAD

**Issue by mvallido** [OneInA1E6/Capstone#10]
The Region's page displays a snippet of information for each Region added into the site.

The name, amount of accommodations within the region, and the amount of bookings that
have been assigned to the region are all displayed, with an Edit button allowing for full viewing and editing of each region, just like the Groups and Accommodations pages above.

- List Regions
    - Name of region
    - Amount of accommodations
    - Number bookings
    - Number of available rooms
- Create Region
    - Name of region
    - Link accommodation to region

**Comment by GMcLachlan45** [comment]
Taking this just as a little break to form revamps.
