### ISSUE TITLE
Req. Report - List of Functional and Non-Functional Requirements

### ISSUE THREAD

**Issue by mvallido** [OneInA1E6/Capstone#26]
- A detailed list of functional requirements for each milestone. Be sure to separate out the functional requirements for each system component based on the target milestone.
- A detailed list of non-functional requirements and environmental constraints for the overall project. The environmental constrains are similar to non-functional requirements and explains the constrains related to system’s environment. Some examples are interfaces to other systems, COTS components, programming language, system's location, size, power consumption, humidity, maintenance accessibility, ...etc.

**Comment by KentonMewling** [comment]
Looks good. Good job!
